CREATE TABLE "hrm_claim_duplicate_signal" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"claimId" text NOT NULL,
	"signalKind" text NOT NULL,
	"matchedClaimId" text,
	"score" numeric(8, 4) NOT NULL,
	"signalPayload" jsonb,
	"reviewDecision" text DEFAULT 'pending' NOT NULL,
	"overrideReason" text,
	"reviewedByUserId" text,
	"reviewedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hrm_compliance_exception" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"employeeId" text,
	"complianceArea" text NOT NULL,
	"itemType" text NOT NULL,
	"sourceReferenceId" text,
	"title" text NOT NULL,
	"severity" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"correctiveActionOwnerUserId" text,
	"correctiveActionDueDate" date,
	"correctiveActionDescription" text,
	"isAutoGenerated" boolean DEFAULT false NOT NULL,
	"resolvedAt" timestamp,
	"resolvedByUserId" text,
	"waivedAt" timestamp,
	"waivedByUserId" text,
	"waiverReason" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"createdByUserId" text,
	"updatedByUserId" text
);
--> statement-breakpoint
CREATE TABLE "hrm_compliance_filing" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"title" text NOT NULL,
	"filingCategory" text NOT NULL,
	"countryCode" text,
	"legalEntityName" text,
	"filingAuthority" text,
	"referenceCode" text,
	"dueDate" date NOT NULL,
	"coveragePeriod" text,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"submittedAt" timestamp,
	"submittedByUserId" text,
	"confirmedAt" timestamp,
	"confirmationReference" text,
	"evidenceDocumentId" text,
	"waiverReason" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"createdByUserId" text,
	"updatedByUserId" text
);
--> statement-breakpoint
CREATE TABLE "hrm_expense_fund" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"currency" text DEFAULT 'MYR' NOT NULL,
	"fundKind" text DEFAULT 'petty_cash' NOT NULL,
	"state" text DEFAULT 'active' NOT NULL,
	"custodianEmployeeId" text,
	"floatLimit" numeric(15, 2),
	"currentBalance" numeric(15, 2) DEFAULT '0' NOT NULL,
	"defaultCostCenterCode" text,
	"defaultFinanceAccountCode" text,
	"defaultProjectCode" text,
	"defaultTaxTreatment" text DEFAULT 'non_taxable_reimbursement' NOT NULL,
	"eligibilityRules" jsonb,
	"policyRules" jsonb,
	"policyVersion" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"createdByUserId" text,
	"updatedByUserId" text
);
--> statement-breakpoint
CREATE TABLE "hrm_policy_acknowledgement" (
	"id" text PRIMARY KEY NOT NULL,
	"organizationId" text NOT NULL,
	"employeeId" text NOT NULL,
	"policyId" text NOT NULL,
	"policyVersion" text NOT NULL,
	"acknowledgedAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "hrm_benefit" ADD COLUMN "benefitCategory" text;--> statement-breakpoint
ALTER TABLE "hrm_benefit" ADD COLUMN "providerId" text;--> statement-breakpoint
ALTER TABLE "hrm_benefit" ADD COLUMN "scopeCountryCodes" jsonb;--> statement-breakpoint
ALTER TABLE "hrm_benefit" ADD COLUMN "scopeLegalEntityCodes" jsonb;--> statement-breakpoint
ALTER TABLE "hrm_benefit_enrollment" ADD COLUMN "effectiveTo" timestamp;--> statement-breakpoint
ALTER TABLE "hrm_benefit_enrollment" ADD COLUMN "documentIds" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "hrm_benefit_enrollment" ADD COLUMN "eligibilityOverrideApprovedByUserId" text;--> statement-breakpoint
ALTER TABLE "hrm_benefit_enrollment" ADD COLUMN "eligibilityOverrideReason" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "expenseFundId" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "reimbursementMode" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "requestedAmount" numeric(15, 2);--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "approvedAmount" numeric(15, 2);--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "rejectedAmount" numeric(15, 2);--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "offsetAmount" numeric(15, 2);--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "claimCurrency" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "reimbursementCurrency" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "fxRate" numeric(18, 8);--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "fxRateAsOf" timestamp;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "fxRateSource" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "fxSnapshot" jsonb;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "eligibilitySnapshot" jsonb;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "validationFlags" jsonb;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "requiresExceptionApproval" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "exceptionApprovedByUserId" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "exceptionApprovedAt" timestamp;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "exceptionReason" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "duplicateReviewStatus" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "returnedReason" text;--> statement-breakpoint
ALTER TABLE "hrm_claim" ADD COLUMN "paymentReference" text;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "verificationStatus" text DEFAULT 'pending' NOT NULL;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "verifiedByUserId" text;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "verifiedAt" timestamp;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "rejectionReason" text;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "versionNumber" integer;--> statement-breakpoint
ALTER TABLE "hrm_document" ADD COLUMN "isMandatory" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "hrm_claim_duplicate_signal" ADD CONSTRAINT "hrm_claim_duplicate_signal_claimId_hrm_claim_id_fk" FOREIGN KEY ("claimId") REFERENCES "public"."hrm_claim"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hrm_claim_duplicate_signal" ADD CONSTRAINT "hrm_claim_duplicate_signal_matchedClaimId_hrm_claim_id_fk" FOREIGN KEY ("matchedClaimId") REFERENCES "public"."hrm_claim"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hrm_compliance_exception" ADD CONSTRAINT "hrm_compliance_exception_employeeId_hrm_employee_id_fk" FOREIGN KEY ("employeeId") REFERENCES "public"."hrm_employee"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hrm_compliance_filing" ADD CONSTRAINT "hrm_compliance_filing_evidenceDocumentId_hrm_document_id_fk" FOREIGN KEY ("evidenceDocumentId") REFERENCES "public"."hrm_document"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hrm_expense_fund" ADD CONSTRAINT "hrm_expense_fund_custodianEmployeeId_hrm_employee_id_fk" FOREIGN KEY ("custodianEmployeeId") REFERENCES "public"."hrm_employee"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hrm_policy_acknowledgement" ADD CONSTRAINT "hrm_policy_acknowledgement_employeeId_hrm_employee_id_fk" FOREIGN KEY ("employeeId") REFERENCES "public"."hrm_employee"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "hrm_claim_duplicate_signal_org_claim_idx" ON "hrm_claim_duplicate_signal" USING btree ("organizationId","claimId");--> statement-breakpoint
CREATE INDEX "hrm_compliance_exception_org_status_idx" ON "hrm_compliance_exception" USING btree ("organizationId","status");--> statement-breakpoint
CREATE INDEX "hrm_compliance_exception_org_employee_idx" ON "hrm_compliance_exception" USING btree ("organizationId","employeeId");--> statement-breakpoint
CREATE INDEX "hrm_compliance_filing_org_status_due_idx" ON "hrm_compliance_filing" USING btree ("organizationId","status","dueDate");--> statement-breakpoint
CREATE UNIQUE INDEX "hrm_expense_fund_org_code_uidx" ON "hrm_expense_fund" USING btree ("organizationId","code");--> statement-breakpoint
CREATE INDEX "hrm_expense_fund_org_state_idx" ON "hrm_expense_fund" USING btree ("organizationId","state");--> statement-breakpoint
CREATE UNIQUE INDEX "hrm_policy_ack_org_employee_policy_version_uidx" ON "hrm_policy_acknowledgement" USING btree ("organizationId","employeeId","policyId","policyVersion");