-- Migration 0017: hrm_compliance_evidence
-- One row per (org, period, countryCode, packType).
-- Generated by payroll-finalize workflow; reproducible from inputHash + rulePackVersion.

CREATE TABLE IF NOT EXISTS "hrm_compliance_evidence" (
  "id"                   text        PRIMARY KEY,
  "organizationId"       text        NOT NULL,
  "periodId"             text        REFERENCES "hrm_payroll_period"("id") ON DELETE RESTRICT,
  "countryCode"          text        NOT NULL,
  "packType"             text        NOT NULL,
  "inputHash"            text        NOT NULL,
  "outputHash"           text        NOT NULL,
  "payloadDocumentId"    text        REFERENCES "hrm_document"("id") ON DELETE SET NULL,
  "rulePackVersion"      text        NOT NULL,
  "generatedAt"          timestamp   NOT NULL DEFAULT now(),
  "generatedByUserId"    text,
  "generatedByRunId"     text,
  "submissionState"      text        NOT NULL DEFAULT 'draft',
  "submissionDeliveryId" text,
  "externalReference"    text,
  "createdAt"            timestamp   NOT NULL DEFAULT now(),
  "updatedAt"            timestamp   NOT NULL DEFAULT now(),
  "createdByUserId"      text,
  "updatedByUserId"      text
);

-- Unique: one pack per org × period × country × type
CREATE UNIQUE INDEX "hrm_compliance_evidence_org_period_country_type_uidx"
  ON "hrm_compliance_evidence"("organizationId", "periodId", "countryCode", "packType");

-- Fast lookup: compliance inbox by state
CREATE INDEX "hrm_compliance_evidence_org_state_generated_idx"
  ON "hrm_compliance_evidence"("organizationId", "submissionState", "generatedAt" DESC);
