import "server-only"

import { and, eq, gte, lte } from "drizzle-orm"

import { db } from "#lib/db"
import { hrmAttendanceDay, hrmAttendanceEvent } from "#lib/db/schema"

import { listVerifiedRemoteCheckinsForEmployeeDate } from "./geolocation.queries.server"

/**
 * Aggregate worked-minute totals from approved remote check-ins for an
 * employee in a date range. Reads from `hrm_attendance_day` (already
 * regenerated by the aggregator) and is therefore the single source of
 * truth for payroll-grade hours from remote check-ins.
 */
export async function getRemoteCheckinHoursForEmployeeDateRange(input: {
  organizationId: string
  employeeId: string
  rangeStart: string
  rangeEnd: string
}): Promise<{
  readonly workedMinutes: number
  readonly overtimeMinutes: number
  readonly verifiedDayCount: number
}> {
  const rows = await db
    .select({
      workedMinutes: hrmAttendanceDay.workedMinutes,
      overtimeMinutes: hrmAttendanceDay.overtimeMinutes,
    })
    .from(hrmAttendanceDay)
    .where(
      and(
        eq(hrmAttendanceDay.organizationId, input.organizationId),
        eq(hrmAttendanceDay.employeeId, input.employeeId),
        gte(hrmAttendanceDay.attendanceDate, input.rangeStart),
        lte(hrmAttendanceDay.attendanceDate, input.rangeEnd)
      )
    )

  let workedMinutes = 0
  let overtimeMinutes = 0
  let verifiedDayCount = 0
  for (const row of rows) {
    workedMinutes += row.workedMinutes ?? 0
    overtimeMinutes += row.overtimeMinutes ?? 0
    if ((row.workedMinutes ?? 0) > 0) verifiedDayCount += 1
  }
  return { workedMinutes, overtimeMinutes, verifiedDayCount }
}

export { listVerifiedRemoteCheckinsForEmployeeDate }

/**
 * Convenience helper for the attendance module — returns true when an
 * approved mobile event exists for the given (employee, day).
 */
export async function hasVerifiedRemoteCheckinOnDate(input: {
  organizationId: string
  employeeId: string
  attendanceDate: string
}): Promise<boolean> {
  const start = new Date(`${input.attendanceDate}T00:00:00.000Z`)
  const end = new Date(start)
  end.setUTCDate(end.getUTCDate() + 1)
  const row = await db.query.hrmAttendanceEvent.findFirst({
    where: and(
      eq(hrmAttendanceEvent.organizationId, input.organizationId),
      eq(hrmAttendanceEvent.employeeId, input.employeeId),
      eq(hrmAttendanceEvent.source, "mobile"),
      gte(hrmAttendanceEvent.occurredAt, start),
      lte(hrmAttendanceEvent.occurredAt, end)
    ),
    columns: { id: true },
  })
  return !!row
}
