import "server-only"

import { and, eq, isNull } from "drizzle-orm"

import type { db } from "#lib/db"
import { hrmComplianceException } from "#lib/db/schema"

import type {
  HrmComplianceExceptionArea,
  HrmComplianceExceptionSeverity,
} from "./compliance-status.shared"

export type HrmComplianceDbExecutor = Parameters<
  Parameters<typeof db.transaction>[0]
>[0]

const OPEN_EXCEPTION_STATUSES = [
  "open",
  "corrective_action_assigned",
  "in_progress",
  "escalated",
] as const

export type InsertComplianceExceptionInput = {
  readonly organizationId: string
  readonly employeeId?: string | null
  readonly complianceArea: HrmComplianceExceptionArea | string
  readonly itemType: string
  readonly sourceReferenceId?: string | null
  readonly title: string
  readonly severity: HrmComplianceExceptionSeverity | string
  readonly status?: string
  readonly correctiveActionOwnerUserId?: string | null
  readonly correctiveActionDueDate?: Date | null
  readonly correctiveActionDescription?: string | null
  readonly isAutoGenerated?: boolean
  readonly createdByUserId?: string | null
}

export async function insertComplianceException(
  executor: HrmComplianceDbExecutor,
  input: InsertComplianceExceptionInput
): Promise<string> {
  const id = crypto.randomUUID()
  await executor.insert(hrmComplianceException).values({
    id,
    organizationId: input.organizationId,
    employeeId: input.employeeId ?? null,
    complianceArea: input.complianceArea,
    itemType: input.itemType,
    sourceReferenceId: input.sourceReferenceId ?? null,
    title: input.title,
    severity: input.severity,
    status: input.status ?? "open",
    correctiveActionOwnerUserId: input.correctiveActionOwnerUserId ?? null,
    correctiveActionDueDate: input.correctiveActionDueDate ?? null,
    correctiveActionDescription: input.correctiveActionDescription ?? null,
    isAutoGenerated: input.isAutoGenerated ?? false,
    createdByUserId: input.createdByUserId ?? null,
    updatedByUserId: input.createdByUserId ?? null,
  })
  return id
}

/** Idempotent auto-exception for document expiry watch (one open row per document). */
export async function upsertAutoDocumentComplianceException(
  executor: HrmComplianceDbExecutor,
  input: {
    readonly organizationId: string
    readonly employeeId: string | null
    readonly documentId: string
    readonly title: string
    readonly severity: string
  }
): Promise<string | null> {
  const existing = await executor.query.hrmComplianceException.findFirst({
    where: and(
      eq(hrmComplianceException.organizationId, input.organizationId),
      eq(hrmComplianceException.complianceArea, "document"),
      eq(hrmComplianceException.sourceReferenceId, input.documentId),
      isNull(hrmComplianceException.resolvedAt),
      isNull(hrmComplianceException.waivedAt)
    ),
    columns: { id: true },
  })
  if (existing) return existing.id

  return insertComplianceException(executor, {
    organizationId: input.organizationId,
    employeeId: input.employeeId,
    complianceArea: "document",
    itemType: "document_expiry",
    sourceReferenceId: input.documentId,
    title: input.title,
    severity: input.severity,
    isAutoGenerated: true,
  })
}

export async function resolveComplianceException(
  executor: HrmComplianceDbExecutor,
  input: {
    readonly organizationId: string
    readonly exceptionId: string
    readonly resolvedByUserId: string
  }
): Promise<boolean> {
  const updated = await executor
    .update(hrmComplianceException)
    .set({
      status: "resolved",
      resolvedAt: new Date(),
      resolvedByUserId: input.resolvedByUserId,
      updatedAt: new Date(),
      updatedByUserId: input.resolvedByUserId,
    })
    .where(
      and(
        eq(hrmComplianceException.organizationId, input.organizationId),
        eq(hrmComplianceException.id, input.exceptionId),
        isNull(hrmComplianceException.resolvedAt),
        isNull(hrmComplianceException.waivedAt)
      )
    )
    .returning({ id: hrmComplianceException.id })
  return updated.length > 0
}

export async function waiveComplianceException(
  executor: HrmComplianceDbExecutor,
  input: {
    readonly organizationId: string
    readonly exceptionId: string
    readonly waiverReason: string
    readonly waivedByUserId: string
  }
): Promise<boolean> {
  const updated = await executor
    .update(hrmComplianceException)
    .set({
      status: "waived",
      waiverReason: input.waiverReason,
      waivedAt: new Date(),
      waivedByUserId: input.waivedByUserId,
      updatedAt: new Date(),
      updatedByUserId: input.waivedByUserId,
    })
    .where(
      and(
        eq(hrmComplianceException.organizationId, input.organizationId),
        eq(hrmComplianceException.id, input.exceptionId),
        isNull(hrmComplianceException.resolvedAt),
        isNull(hrmComplianceException.waivedAt)
      )
    )
    .returning({ id: hrmComplianceException.id })
  return updated.length > 0
}

export { OPEN_EXCEPTION_STATUSES }
