/**
 * Writes `.openstatus/ci.yaml` monitor IDs for GitHub Synthetics (numeric IDs).
 *
 * Requires OPENSTATUS_API_TOKEN. Loads via `pnpm env:sync` + `.env.local`, then:
 *
 *   node scripts/with-env.mjs node scripts/openstatus-sync-ci.mjs
 *
 * Filters to HTTP monitors whose URL contains `nexuscanon.com` (Afenda prod monitors).
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { createOpenStatusClient } from "@openstatus/sdk-node"

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..")
const outPath = path.join(root, ".openstatus", "ci.yaml")

const token = process.env.OPENSTATUS_API_TOKEN?.trim()
if (!token) {
  console.error(
    "[openstatus-sync-ci] Missing OPENSTATUS_API_TOKEN — set in `.env.config`, run `pnpm env:sync`, then re-run with:\n" +
      "  node scripts/with-env.mjs node scripts/openstatus-sync-ci.mjs"
  )
  process.exit(1)
}

const client = createOpenStatusClient({ apiKey: token })

/** @type {number[]} */
const ids = []
let offset = 0
const limit = 100

for (;;) {
  const { httpMonitors, totalSize } =
    await client.monitor.v1.MonitorService.listMonitors({
      limit,
      offset,
    })

  for (const http of httpMonitors ?? []) {
    const id = Number(http.id)
    if (!Number.isFinite(id) || id <= 0) continue
    const url = http.url ?? ""
    if (!url.includes("nexuscanon.com")) continue
    if (http.active === false) continue
    ids.push(id)
  }

  offset += limit
  if (!totalSize || offset >= Number(totalSize)) break
}

ids.sort((a, b) => a - b)

const unique = [...new Set(ids)]

const yaml =
  `# OpenStatus GitHub Action config — generated by scripts/openstatus-sync-ci.mjs\n` +
  `# Re-run after changing monitors: node scripts/with-env.mjs node scripts/openstatus-sync-ci.mjs\n` +
  `tests:\n` +
  `  ids:\n` +
  unique.map((n) => `    - ${n}\n`).join("")

fs.writeFileSync(outPath, yaml, "utf8")
console.log(
  `[openstatus-sync-ci] Wrote ${unique.length} monitor id(s) → ${path.relative(root, outPath)}`
)
