/**
 * Syncs maintainer-managed `.env.config` → `.env.local` for Next.js local dev.
 *
 * - Next.js load order: `.env` → `.env.local` → `.env.[mode]` → `.env.[mode].local`
 * - Keys defined in `.env.config` always win (re-run sync after editing `.env.config`).
 * - Variables present only in an existing `.env.local` are preserved under a footer section
 *   (machine-only secrets not tracked in `.env.config`).
 *
 * Drizzle CLI reads the same vars via `drizzle.config.ts`, which loads `.env.local` first.
 *
 * Usage: pnpm env:sync
 *        pnpm env:sync -- --dry-run
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..")
const srcPath = path.join(root, ".env.config")
const destPath = path.join(root, ".env.local")

const dryRun = process.argv.includes("--dry-run")

/** @returns {Record<string, string>} */
function parseDotenv(content) {
  /** @type {Record<string, string>} */
  const out = {}
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith("#")) continue
    const eq = line.indexOf("=")
    if (eq <= 0) continue
    const key = line.slice(0, eq).trim()
    let val = line.slice(eq + 1).trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    out[key] = val
  }
  return out
}

/** @param {string} val */
function formatEnvValue(val) {
  if (val === "") return ""
  if (/[\r\n#"'\s\\]/.test(val)) {
    return `"${val.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
  }
  return val
}

/** @param {Record<string, string>} parsedConfig */
function warnIfMissing(parsedConfig) {
  const critical = [
    "DATABASE_URL",
    "NEON_AUTH_BASE_URL",
    "NEON_AUTH_COOKIE_SECRET",
  ]
  for (const key of critical) {
    const v = parsedConfig[key]
    if (v === undefined || v === "") {
      console.warn(
        `[env:sync] Warning: ${key} is empty — auth or DB may fail locally.`
      )
    }
  }

  const site =
    parsedConfig.NEXT_PUBLIC_SITE_URL?.trim() ||
    parsedConfig.NEXT_PUBLIC_APP_URL?.trim()
  if (!site) {
    console.warn(
      "[env:sync] Warning: NEXT_PUBLIC_SITE_URL and NEXT_PUBLIC_APP_URL are both empty — metadataBase / OG URLs may be wrong."
    )
  }

  const neonAuthBase = parsedConfig.NEON_AUTH_BASE_URL?.trim()
  const neonPublicProxy = parsedConfig.NEXT_PUBLIC_AUTH_URL?.trim()
  if (neonAuthBase && !neonPublicProxy) {
    console.warn(
      "[env:sync] Warning: NEON_AUTH_BASE_URL is set but NEXT_PUBLIC_AUTH_URL is empty — " +
        "the browser auth client should target the app proxy; set NEXT_PUBLIC_AUTH_URL to your site origin + /api/auth " +
        "(see .env.config.example §I)."
    )
  }

  const neonAuthOn =
    parsedConfig.AFENDA_NEON_AUTH_ENABLED?.trim() === "1" ||
    parsedConfig.NEXT_PUBLIC_AFENDA_NEON_AUTH_ENABLED?.trim() === "1" ||
    Boolean(neonAuthBase)
  if (neonAuthOn) {
    console.warn(
      "[env:sync] Neon Auth V2: ensure the Postgres branch behind DATABASE_URL has the neon_auth schema " +
        "(Neon Console → Branch → Auth). Preview/dev branches often omit it until Auth is enabled there. " +
        "Run Drizzle migrations on that branch for app tables + pgvector (pnpm db:migrate:local). See AGENTS.md § Neon checklist."
    )
  }
}

if (!fs.existsSync(srcPath)) {
  console.error(
    "[env:sync] Missing .env.config.\n" +
      "  Copy .env.config.example → .env.config and fill in values, then run again."
  )
  process.exit(1)
}

const configBody = fs.readFileSync(srcPath, "utf8")
const parsedConfig = parseDotenv(configBody)
const configKeySet = new Set(Object.keys(parsedConfig))

/** Keys only in existing .env.local (not in .env.config) — preserved across sync. */
/** @type {Record<string, string>} */
const preserved = {}

if (fs.existsSync(destPath)) {
  const prevRaw = fs.readFileSync(destPath, "utf8")
  const prevParsed = parseDotenv(prevRaw)
  for (const [k, v] of Object.entries(prevParsed)) {
    if (!configKeySet.has(k)) {
      preserved[k] = v
    }
  }
}

const banner =
  `# Generated by pnpm env:sync — do not edit keys that live in .env.config.\n` +
  `# Source: .env.config (${new Date().toISOString()})\n` +
  `# Next.js: .env.local | Drizzle: loaded from .env.local in drizzle.config.ts\n` +
  `\n`

let out = banner + configBody.replace(/\s+$/, "") + "\n"

if (Object.keys(preserved).length > 0) {
  out +=
    `\n# --- Not in .env.config (kept from previous .env.local) ---\n` +
    Object.entries(preserved)
      .map(([k, v]) => `${k}=${formatEnvValue(v)}`)
      .join("\n") +
    "\n"
}

if (dryRun) {
  console.log("[env:sync] Dry run — would write .env.local:\n")
  console.log(out)
  warnIfMissing(parsedConfig)
  process.exit(0)
}

fs.writeFileSync(destPath, out, "utf8")
console.log(
  "[env:sync] Wrote .env.local from .env.config" +
    (Object.keys(preserved).length > 0
      ? ` (+ ${Object.keys(preserved).length} local-only key(s))`
      : "") +
    "."
)
warnIfMissing(parsedConfig)
console.log("[env:sync] Restart `pnpm dev` if running.")
